// Mocks generated by Mockito 5.2.0 from annotations
// in pokedex_app/test/features/pokemons_list/data/repositories/pokemons_list_repo_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pokedex_app/core/data/datasources/core_local_data_source.dart'
    as _i6;
import 'package:pokedex_app/core/data/models/pokemon_model.dart' as _i5;
import 'package:pokedex_app/core/data/models/pokemon_page_model.dart' as _i2;
import 'package:pokedex_app/core/network/network_info.dart' as _i7;
import 'package:pokedex_app/features/pokemons_list/data/datasources/pokemons_remote_data_source.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakePokemonPageModel_0 extends _i1.Fake implements _i2.PokemonPageModel {
}

/// A class which mocks [PokemonsRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonsRemoteDataSource extends _i1.Mock
    implements _i3.PokemonsRemoteDataSource {
  MockPokemonsRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.PokemonPageModel> fetchPokemonsPage(int? pageNo) =>
      (super.noSuchMethod(Invocation.method(#fetchPokemonsPage, [pageNo]),
              returnValue:
                  Future<_i2.PokemonPageModel>.value(_FakePokemonPageModel_0()))
          as _i4.Future<_i2.PokemonPageModel>);
  @override
  _i4.Future<List<_i5.PokemonModel>> fetchPokemonsDetailsList(
          List<String>? linksList) =>
      (super.noSuchMethod(
              Invocation.method(#fetchPokemonsDetailsList, [linksList]),
              returnValue:
                  Future<List<_i5.PokemonModel>>.value(<_i5.PokemonModel>[]))
          as _i4.Future<List<_i5.PokemonModel>>);
}

/// A class which mocks [CoreLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCoreLocalDataSource extends _i1.Mock
    implements _i6.CoreLocalDataSource {
  MockCoreLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<int>> fetchFavoritesPokemonsIds() => (super.noSuchMethod(
      Invocation.method(#fetchFavoritesPokemonsIds, []),
      returnValue: Future<List<int>>.value(<int>[])) as _i4.Future<List<int>>);
  @override
  _i4.Future<int> storeFavoritePokemon(int? pokemonID) =>
      (super.noSuchMethod(Invocation.method(#storeFavoritePokemon, [pokemonID]),
          returnValue: Future<int>.value(0)) as _i4.Future<int>);
  @override
  _i4.Future<void> removeFromFavorites(int? pokemonID) =>
      (super.noSuchMethod(Invocation.method(#removeFromFavorites, [pokemonID]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i7.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
}
