// Mocks generated by Mockito 5.2.0 from annotations
// in pokedex_app/test/features/pokemons_list/domain/usecase/fetch_pokemons_page_usecase_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pokedex_app/core/data/models/pokemon_model.dart' as _i7;
import 'package:pokedex_app/core/data/models/pokemon_page_model.dart' as _i6;
import 'package:pokedex_app/core/errors/failure.dart' as _i5;
import 'package:pokedex_app/features/pokemons_list/domain/repositories/pokemons_list_repo.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [PokemonsListRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonsListRepository extends _i1.Mock
    implements _i3.PokemonsListRepository {
  MockPokemonsListRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.PokemonPageModel>> fetchPokemonsPage(
          int? pageNo) =>
      (super.noSuchMethod(Invocation.method(#fetchPokemonsPage, [pageNo]),
              returnValue:
                  Future<_i2.Either<_i5.Failure, _i6.PokemonPageModel>>.value(
                      _FakeEither_0<_i5.Failure, _i6.PokemonPageModel>()))
          as _i4.Future<_i2.Either<_i5.Failure, _i6.PokemonPageModel>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.PokemonModel>>>
      fetchPokemonsDetails(List<String>? linksList) => (super.noSuchMethod(
              Invocation.method(#fetchPokemonsDetails, [linksList]),
              returnValue:
                  Future<_i2.Either<_i5.Failure, List<_i7.PokemonModel>>>.value(
                      _FakeEither_0<_i5.Failure, List<_i7.PokemonModel>>()))
          as _i4.Future<_i2.Either<_i5.Failure, List<_i7.PokemonModel>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.PokemonModel>>>
      fetchFavoritePokemons() => (super.noSuchMethod(
              Invocation.method(#fetchFavoritePokemons, []),
              returnValue:
                  Future<_i2.Either<_i5.Failure, List<_i7.PokemonModel>>>.value(
                      _FakeEither_0<_i5.Failure, List<_i7.PokemonModel>>()))
          as _i4.Future<_i2.Either<_i5.Failure, List<_i7.PokemonModel>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, int>> fetchFavoritesCount() =>
      (super.noSuchMethod(Invocation.method(#fetchFavoritesCount, []),
              returnValue: Future<_i2.Either<_i5.Failure, int>>.value(
                  _FakeEither_0<_i5.Failure, int>()))
          as _i4.Future<_i2.Either<_i5.Failure, int>>);
}
